version: "3.6"
services:
  mysql:
    container_name: cambridge-education-mysql
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10
      start_period: 30s
      
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - cambridge-education
    volumes:
      - ./DATA/sql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - 3306:3306
    restart: always
    logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "3"

  elasticsearch:
    container_name: cambridge-education-es
    image: elasticsearch:7.13.4
    env_file:
      - .env
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.host=0.0.0.0
      - http.port=9200
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - cambridge-education
    ports:
      - 9200:9200
    volumes:
      - ./DATA/es_data:/usr/share/elasticsearch/data/
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs
    restart: always
    logging:
        driver: "json-file"
        options:
          max-size: "50m"

  kibana:
    container_name: cambridge-education-kibana
    image: kibana:7.13.4
    env_file:
      - .env
    environment:
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - cambridge-education
    ports:
      - 5601:5601
    restart: always
    logging:
        driver: "json-file"
        options:
          max-size: "50m"

  backend:
    container_name: cambridge-education-interview-backend
    build: ./cambridge_education_interview
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - ./cambridge_education_interview:/project
      - ./logs/backend:/project/logs
    networks:
        - cambridge-education
    ports:
      - 83:8000
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    logging:
        driver: "local"
        options:
          max-size: "50m"

networks:
  cambridge-education:
    driver: bridge
