# Generated by Django 4.0.4 on 2025-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
