# Generated by Django 4.0.4 on 2025-01-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_account', '0003_chatrroom_hobby_interest_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='location',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='經度'),
        ),
    ]
